export const SET_LOCATION_PERMISSION = 'permission/SET_LOCATION_PERMISSION';
export const CHECK_PERMISSION_LOCATION = 'permission/CHECK_PERMISSION_LOCATION';
export const CLEAR_PERMISSION_LOCATION = 'permission/CLEAR_PERMISSION_LOCATION';

